<?php
$files = 'admin-notice.css
        admin-notice.css.map
        admin-style.css
        admin-style.css.map
        chatgpt.css
        chatgpt.css.map
        color-picker.css
        color-picker.css.map
        colors.css
        colors.css.map
        control.css
        control.css.map
        core.css
        core.css.map
        editormd.css
        editormd.css.map
        elusive-icons.css
        elusive-icons.css.map
        field_social_profiles_frontend.css
        field_social_profiles_frontend.css.map
        githuber-md.css
        githuber-md.css.map
        gradient-filters.css
        gradient-filters.css.map
        image-filters.css
        image-filters.css.map
        jquery-ui-1.10.0.custom.css
        jquery-ui-1.10.0.custom.css.map
        layout.css
        layout.css.map
        layouts.css
        main.css
        main.css.map
        markdown-theme-github.css
        markdown-theme-github.css.map
        media.css
        media.css.map
        messages.css
        messages.css.map
        nouislider.css
        nouislider.css.map
        qtip.css
        qtip.css.map
        redux-accordion.css
        redux-accordion.css.map
        redux-ace-editor.css
        redux-ace-editor.css.map
        redux-admin.css
        redux-admin.css.map
        redux-background.css
        redux-background.css.map
        redux-border.css
        redux-border.css.map
        redux-box-shadow.css
        redux-box-shadow.css.map
        redux-checkbox.css
        redux-checkbox.css.map
        redux-color-gradient.css
        redux-color-gradient.css.map
        redux-color-palette.css
        redux-color-palette.css.map
        redux-color-rgba.css
        redux-color-rgba.css.map
        redux-color-scheme.css
        redux-color-scheme.css.map
        redux-content.css
        redux-content.css.map
        redux-custom-fonts.css
        redux-custom-fonts.css.map
        redux-date.css
        redux-date.css.map
        redux-datetime.css
        redux-datetime.css.map
        redux-dimensions.css
        redux-dimensions.css.map
        redux-divide.css
        redux-divide.css.map
        redux-editor.css
        redux-editor.css.map
        redux-extension-customizer.css
        redux-extension-customizer.css.map
        redux-extension-metaboxes.css
        redux-extension-metaboxes.css.map
        redux-extension-search.css
        redux-extension-search.css.map
        redux-extension-taxonomy.css
        redux-extension-taxonomy.css.map
        redux-extension-users.css
        redux-extension-users.css.map
        redux-extension-widget-areas.css
        redux-extension-widget-areas.css.map
        redux-google-maps.css
        redux-google-maps.css.map
        redux-icon-select.css
        redux-icon-select.css.map
        redux-image-select.css
        redux-image-select.css.map
        redux-import-export.css
        redux-import-export.css.map
        redux-info.css
        redux-info.css.map
        redux-link-color.css
        redux-link-color.css.map
        redux-media.css
        redux-media.css.map
        redux-multi-media.css
        redux-multi-media.css.map
        redux-multi-text.css
        redux-multi-text.css.map
        redux-my-extension.css
        redux-my-extension.css.map
        redux-options-object.css
        redux-options-object.css.map
        redux-palette.css
        redux-palette.css.map
        redux-repeater.css
        redux-repeater.css.map
        redux-section.css
        redux-section.css.map
        redux-select-image.css
        redux-select-image.css.map
        redux-select.css
        redux-select.css.map
        redux-slider.css
        redux-slider.css.map
        redux-slides.css
        redux-slides.css.map
        redux-social-profiles.css
        redux-social-profiles.css.map
        redux-sortable.css
        redux-sortable.css.map
        redux-sorter.css
        redux-sorter.css.map
        redux-spacing.css
        redux-spacing.css.map
        redux-spinner.css
        redux-spinner.css.map
        redux-switch.css
        redux-switch.css.map
        redux-tabbed.css
        redux-tabbed.css.map
        redux-text.css
        redux-text.css.map
        redux-typography.css
        redux-typography.css.map
        redux-welcome.css
        redux-welcome.css.map
        rtl.css
        rtl.css.map
        select2.css
        select2.css.map
        settings.css
        settings.css.map
        spectrum.css
        spectrum.css.map
        timeless.css
        timeless.css.map
        vendor.css
        vendor.css.map';

$files = explode("\n", $files);
foreach ($files as $file) {
    $file = trim($file);
    if (empty($file)) {
        continue;
    }
    // $file = 'wp-content/themes/deljdlx-taverne/assets/css/' . $file;
    if (file_exists($file)) {
        echo $file . "\n";
        unlink($file);
    }
}